*** empty log message ***

diff --git a/oralux/install/packages/knoppix/saveconfig b/oralux/install/packages/knoppix/saveconfig
--- a/oralux/install/packages/knoppix/saveconfig
+++ b/oralux/install/packages/knoppix/saveconfig
@@ -2,192 +2,102 @@
 # saveconfig - create KNOPPIX configuration floppy
 # (C) Klaus Knopper Mar 2002
 # Spanish translation by Luis Llorente, luis.llorente@hispalinux.es
-# 2003 Gilles Casse: A few changes for Oralux
+# 2003, 2004 Gilles Casse: Changes for Oralux
 # * French translation
-# * No dialog boxes
+# * The new config is compared to the old one (via their md5sum)
+# * /etc/fstab is not stored
+#
 # Sep 2003: 
 # German translations by Guenther Harrasser.
 # Spanish translations by Fernando Pinto da Silva.
 #
-
-yesOrNo(){
-    case $LANGUAGE in
-        fr*)
-            YES1="o"
-            YES2="O"
-            NO1="n"
-            NO2="N"
-            SENTENCE="Si oui tapez sur la touche o, si non tapez sur n. Appuyer ensuite sur la touche Entrée"
-            ;;
-        *)
-            YES1="y"
-            YES2="Y"
-            NO1="n"
-            NO2="N"
-            echo "Please, press key $YES1 or $NO1. Then, press the return key" 
-            ;;
-    esac
-
-    read=1
-
-    while [ "$read" == "1" ]; do
-        echo $SENTENCE 
-        read c
-
-        case $c in
-            $YES1|$YES2)
-                ANSWER=0
-                read=0;;
-
-            $NO1|$NO2)
-                ANSWER=1
-                read=0;;
-        esac
-    done
-
-    return $ANSWER
-}
+set -v 
+export DIALOG="/usr/bin/php5 /usr/share/oralux/main/dialog.php"
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 export PATH
 
-XDIALOG_HIGH_DIALOG_COMPAT=1
-export XDIALOG_HIGH_DIALOG_COMPAT
-
 # Get root
 [ "`id -u`" != "0" ] && exec sudo "$0" "$@"
 
-TMP="/tmp/saveconfig.tmp$$"
+oldList=`tempfile 2>/dev/null`
+newList=`tempfile 2>/dev/null`
+TMP=`tempfile 2>/dev/null`
 
 bailout(){
-rm -f "$TMP" "$TMP.done" "$TMP.err"
-umount "$DIRECTORY" 2>/dev/null
+rm -f "$oldList" "$newList" "$TMP" "$TMP.err" "/tmp/configs.tbz"
 exit 0
 }
 
 trap bailout 1 2 3 15
 
-# LANGUAGE etc.
-[ -f /etc/sysconfig/knoppix ] && . /etc/sysconfig/knoppix
-[ -z "$LANG" ] && export LANG
-[ -z "$LANGUAGE" ] && export LANGUAGE
-[ -z "$CHARSET" ] && export CHARSET
+FLOPPYDIR="$(ls -l /mnt/floppy | awk '{print $NF}')"
 
-DESKTOPKB="$(du -sk $HOME/Desktop 2>/dev/null | awk '{print $1}')"
+umountfloppy(){
+#mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
+mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
+}
 
-# Language-dependent Messages
-case "$LANGUAGE" in
-de*|at*|ch*)
-TITLE1="KNOPPIX Konfigurationsarchiv anlegen."
-MESSAGE1="Wollen Sie folgende Konfigurationsdateien speichern:"
-MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
-MESSAGE3="Archiviere geänderte Konfigurationsdateien..."
-# MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
-DIRECTORY_MSG1="Verzeichnis"
-DIRECTORY_MSG2="Tippen Sie bitte die Nummer des Verzeichnisses wo die Konfigurationsdateien gespeichert werden"
-E1="Persönliche Einstellungen (Desktop, Programme)"
-E2="Netzwerk Einstellungen (LAN, Modem, ISDN, ASDL)"
-# E3="Grafik Subsystem Einstellungen (XF86Config)"
-E4="Weitere systemweite Einstellungen (Drucker etc.)"
-# E5="Alle Desktop-Dateien (${DESKTOPKB}kB)"
-ERROR="Leider konnte die KNOPPIX-Konfiguration NICHT gespeichert werden:"
-;;
+# Try to mount this filesystem read-only
+trymount(){
+# Check if already mounted
+case "$(cat /proc/mounts)" in *\ $2\ *) return 0;; esac
+# Apparently, mount-aes DOES autodetect AES loopback files.
+[ -b "$1" ] && { mount -t auto -o ro "$1" "$2" 2>/dev/null; RC="$?"; }
+# We need to mount crypto-loop files with initial rw support
+[ -f "$1" ] && { mount -t auto -o loop,rw "$1" "$2" 2>/dev/null; RC="$?"; }
+# Mount succeeded?
+[ "$RC" = "0" ] && return 0
+return 1
+}
 
-es*)
-TITLE1="Crear un archivo de configuración de KNOPPIX."
-MESSAGE1="¿Desea guardar los siguientes archivos de configuración ?"
-MESSAGE2="Inserte un disquete vacío formateado para DOS o ext2."
-MESSAGE3="Guardando archivos de configuración..."
-# MESSAGE4="Seleccione el directorio para guardar los archivos de configuración."
-DIRECTORY_MSG1="Directorio"
-DIRECTORY_MSG2="Teclee el número del directorio donde se almazenarán los archivos de configuración"
-E1="Configuración personal (escritorio, programas)"
-E2="Configuración de Red (internet, intranet)"
-# E3="Parametros gráficos (XF86Config)"
-E4="Otra configuración del sistema (impresora, etc.)"
-# E5="Todos los archivos en el Escritorio (${DESKTOPKB}kB)"
-ERROR="No se pudo guardar la configuración de KNOPPIX:"
-;;
-
-fr*)
-TITLE1="Création d'une archive pour la configuration KNOPPIX."
-MESSAGE1="Souhaitez-vous sauvegarder les fichiers de configuration suivants :"
-MESSAGE2="Insérez s'il vous plait une disquette déjà formattée DOS ou ext2, et inscriptible."
-MESSAGE3="Sauvegarde en cours..."
-# MESSAGE4="Choisissez, s'il vous plait, le répertoire de sauvegarde des fichiers de configuration :"
-DIRECTORY_MSG1="Répertoire"
-DIRECTORY_MSG2="Taper le numéro du répertoire où seront stockés les fichiers de configuration"
-E1="Configuration personnelle (bureau, programmes)"
-E2="Paramètres réseau (internet, intranet)"
-# E3="Paramètres graphiques (XF86Config)"
-E4="Autre configuration système (imprimante etc.)"
-# E5="Tous les fichiers sur le bureau (${DESKTOPKB}kB)"
-ERROR="La configuration KNOPPIX n'a pu être sauvée :"
-;;
-*)
-TITLE1="Create KNOPPIX configuration archive."
-MESSAGE1="Do you want to save the following configuration files:"
-MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
-MESSAGE3="Saving configuration archive..."
-# MESSAGE4="Please select directory for saving configuration files:"
-DIRECTORY_MSG1="Directory"
-DIRECTORY_MSG2="Type the number of the directory where will be stored the configuration files"
-E1="Personal configuration (desktop, programs)"
-E2="Network settings (Internet, intranet)"
-# E3="Graphics subsystem settings (XF86Config)"
-E4="Other system configuration (printer etc.)"
-# E5="All files on the Desktop (${DESKTOPKB}kB)"
-ERROR="The KNOPPIX configuration could NOT be saved:"
-;;
-esac
-
-echo $TITLE1
-echo $MESSAGE1
-
-
-FILES=""
-SAVEHOME=""
-# In console mode, I expect nothing in the Desktop directory
-# The question won't be asked. 
-SAVEDESK="yes"
-SAVEETC=""
-SAVENET=""
-# Question wont' be asked
-SAVEX=""
-CHOWNHOME=""
-NETFILES='/etc/network|/etc/ppp|/etc/chat|/etc/isdn|/etc/sysconfig/isdn|/etc/sysconfig/provider|/etc/resolv\.conf|/etc/hosts|/etc/hosts\.|/etc/inetd\.conf'
-XFILES='/etc/X11'
-
-echo $E1
-yesOrNo && SAVEHOME="yes"
-
-# Original default value=Off
-#echo $E5
-#yesOrNo && SAVEDESK="yes"
-
-echo $E2
-yesOrNo && SAVEETC="yes"; SAVENET="yes"
-
-#echo $E3
-#yesOrNo && SAVEETC="yes"; SAVEX="yes"
-
-echo $E4
-yesOrNo && SAVEETC="yes"
-
-[ -n "$SAVEHOME" -o -n "$SAVEDESK" ] && CHOWNHOME="chown -R $(ls -ld $HOME | awk '{print $3"."$4}') $HOME"
-
-# Find changes in (real) files of dir1 ... dir2
 findchanged(){
 if [ -d "$1" ]; then
-for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' )`; do
+for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' | grep -v "~$" )`; do
 cmp -s "$1/$i" "$2/$i" || echo "$1/$i"
+
 done
 elif [ -e "$1" ]; then
 cmp -s "$1" "$2" || echo "$1"
 fi
 }
 
+getNewList(){
+
+    if [ "$1" == "SAVEHOME" ]; then
+	IGNORE="\.ICEauthority|ksycoka|\.xsession-errors|\.DCOP|\.MCOP|kio_http/cache|\.mozilla/.*/Cache/|favicons|office/user/work"
+	for i in $HOME/.??* $HOME/office $HOME/evolution; do findchanged "$i" /etc/skel/$(basename "$i"); done | egrep -v -e '('"$IGNORE"')' > "$newList"
+    fi
+
+#    SAVEDESK=""
+#    [ -n "$SAVEDESK" ] && for i in $HOME/Desktop; do findchanged "$i" /etc/skel/$(basename "$i"); done >> "$newList"
+    
+    IGNORE='/etc/ioctl.save|/etc/fstab|/etc/mtab|/etc/X11/XF86Config-4|/etc/X11/XF86Config'
+    if [ -d /KNOPPIX/etc ]; then
+	findchanged /etc /KNOPPIX/etc | egrep -v -e '('"$IGNORE"')' >>"$newList"
+    fi
+}
+
+getOldList(){
+    source /etc/sysconfig/knoppix
+#RAF
+    MYCONFDEVICE=/dev/sda1
+    MYCONFMOUNTPOINT=/mnt/sda1
+    MYCONFDIR=/mnt/sda1
+
+    if [ -n "$MYCONFDEVICE" ]; then
+	if trymount "$MYCONFDEVICE" "$MYCONFMOUNTPOINT"; then
+	    MYCONFIG="$(ls -1d $MYCONFDIR/[Cc][Oo][Nn][Ff][Ii][Gg][Ss].[Tt][Bb][Zz] 2>/dev/null)"
+	    if [ -n "$MYCONFIG" -a -f "$MYCONFIG" ]; then
+		tar -jpPtf "$MYCONFIG" > $oldList
+	    fi
+	fi
+    fi
+}
+
 writescript(){
+echo writescript $1 $2
+CONFIGSFILE=$2
 cat >"$1" <<EOT
 #!/bin/sh
 [ "\`id -u\`" = "0" ] || { echo "You need root privileges to modify the system!" >&2 ; exit 1; }
@@ -200,86 +110,6 @@ tar -jpPtf "\$CONFIGS" | while read i; do rm -f "\$i"; done
 tar -jpPxf "\$CONFIGS" ; $CHOWNHOME
 fi
 EOT
-return "$?"
-}
-
-FLOPPYDIR="$(ls -l /mnt/floppy | awk '{print $NF}')"
-
-umountfloppy(){
-#mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
-mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
-}
-
-
-PARTITIONS=""
-
-PARTITIONS[1]="/mnt/floppy"
-count=2
-
-# Directory selector
-for i in `awk '/^\/dev\/[hs]d[a-z].*\/mnt\/[hs]d[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`; do
-    PARTITIONS[$count]="$i"
-    count=$(($count+1))
-done
-
-echo $DIRECTORY_MSG2
-
-while [ -z "${PARTITIONS[$c]}" ]
-  do
-  i=1
-  while [ $i -lt $count ]
-  do
-    echo $DIRECTORY_MSG1 $i ${PARTITIONS[$i]}
-    i=$(($i+1))
-  done  
-  read c
-done
-
-DIRECTORY="${PARTITIONS[$c]}"
-
-echo $DIRECTORY
-
-[ -z "$DIRECTORY" -o ! -e "$DIRECTORY" ] && bailout
-
-case "$DIRECTORY" in *floppy*)
-DIRECTORY="$FLOPPYDIR"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-while :; do
-umountfloppy
-echo $MESSAGE2
-yesOrNo || bailout
-
-echo "$FLOPPYDIR" | grep -q auto || mount /mnt/floppy
-[ "$?" = "0" ] && writescript "$KNOPPIXSH" && break
-done
-;;
-*)
-rm -f "$TMP.err"
-mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
-[ "$?" != "0" ] && { echo "$ERROR `cat $TMP.err`"; bailout; }
-mount | grep -q "$DIRECTORY.*ntfs" && { echo "$ERROR NTFS"; bailout; }
-mount -o remount,rw "$DIRECTORY"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-writescript "$KNOPPIXSH"
-esac
-
-rm -f "$TMP"
-touch "$TMP"
-
-[ -n "$SAVEHOME" ] && for i in $HOME/.??* $HOME/office $HOME/evolution; do findchanged "$i" /etc/skel/$(basename "$i"); done | egrep -v -e '(\.ICEauthority|ksycoka|\.xsession-errors|\.DCOP|\.MCOP|kio_http/cache|\.mozilla/.*/Cache/|favicons|office/user/work)' >"$TMP"
-[ -n "$SAVEDESK" ] && for i in $HOME/Desktop; do findchanged "$i" /etc/skel/$(basename "$i"); done >>"$TMP"
-
-IGNORE='/etc/ioctl.save|/etc/mtab'
-
-if [ -n "$SAVEETC" -a -d /KNOPPIX/etc ]; then
-findchanged /etc /KNOPPIX/etc >>"$TMP"
-[ -n "$SAVENET" ] || IGNORE="$IGNORE|$NETFILES"
-[ -n "$SAVEX" ] || IGNORE="$IGNORE|$XFILES"
-fi
-
-rm -f "$TMP.tmp"
-egrep -v -e '('"$IGNORE"')' "$TMP" > "$TMP.tmp"
-mv -f "$TMP.tmp" "$TMP"
 
 SCRIPTS=""
 STARTNET=""
@@ -294,11 +124,11 @@ case "$i" in
 /etc/cups*) STARTCUPS="yes";;
 /etc/inittab) REINIT="yes";;
 esac
-done <"$TMP"
+done <"$newList"
 
-[ -n "$STARTNET" ]    && { echo "killall pump 2>/dev/null && sleep 2 && killall -9 pump 2>/dev/null && sleep 2" >>"$KNOPPIXSH" ; SCRIPTS="$SCRIPTS ifupdown networking"; }
+[ -n "$STARTNET" ] && { echo "killall pump 2>/dev/null && sleep 2 && killall -9 pump 2>/dev/null && sleep 2" >>"$KNOPPIXSH" ; SCRIPTS="$SCRIPTS ifupdown networking"; }
 [ -n "$STARTPCMCIA" ] && echo 'echo "(Re)starting PCMCIA services."; killall cardmgr 2>/dev/null && sleep 4; cardmgr && sleep 4' >>"$KNOPPIXSH"
-[ -n "$STARTCUPS" ]   && SCRIPTS="$SCRIPTS cupsys"
+[ -n "$STARTCUPS" ] && SCRIPTS="$SCRIPTS cupsys"
 
 if [ -n "$SCRIPTS" ]; then
 echo 'echo "Starting daemons..."' >>"$KNOPPIXSH"
@@ -308,7 +138,9 @@ fi
 [ -n "$REINIT" ] && echo 'echo "Reloading INIT." ; init q' >> "$KNOPPIXSH"
 
 rm -f "$TMP.err"
-BZIP2=-9 tar -T - -cpPjf "$DIRECTORY/configs.tbz" <"$TMP" 2>"$TMP.err"
+#BZIP2=-9 tar -T - -cpPjf "$DIRECTORY/configs.tbz" <"$newList" 2>"$TMP.err"
+
+cp "$CONFIGSFILE" "$DIRECTORY/configs.tbz"
 
 RC="$?"
 
@@ -317,25 +149,102 @@ umountfloppy
 else
 umount "$DIRECTORY" 2>/dev/null
 fi
+}
 
-# More language-dependent Messages
-case "$LANGUAGE" in
-de*|at*|ch*)
-SUCCESS="Die KNOPPIX-Konfiguration wurde erfolgreich gespeichert. Ihre Konfigurationsdateien werden beim nächsten Oralux-Bootvorgang in die Ramdisk restauriert."
-;;
-es*)
-SUCCESS="La creación de la configuración de KNOPPIX fue satisfactoria. Sus archivos de configuración se reinstalaran en el próximo arranque de Oralux."
-;;
-fr*)
-SUCCESS="L'archivage de la configuration KNOPPIX a réussi. Vos fichiers de configuration seront réinstallés dans le ramdisk au prochain boot d'Oralux."
+saveNewList(){
+CONFIGS_FILE=$1
+
+MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
+MESSAGE4="Seleccione el directorio para guardar los archivos de configuración."
+MESSAGE4="Choisissez, s'il vous plait, le répertoire de sauvegarde des fichiers de configuration :"    
+MESSAGE4="Please select directory for saving configuration files:"
+
+# Directory selector
+PARTITIONS="/mnt/floppy [Floppy] on"
+for i in `awk '/^\/dev\/[hs]d[a-z].*\/mnt\/[hs]d[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`
+do
+PARTITIONS="$PARTITIONS ${i} [Disk/Partition] off"
+done
+
+echo "PARTITIONS=$PARTITIONS"
+
+rm -f "$TMP"
+$DIALOG --clear --radiolist "$MESSAGE4" 18 75 9 $PARTITIONS 2>"$TMP" || bailout
+
+DIRECTORY=`cat $TMP`
+
+[ -z "$DIRECTORY" -o ! -e "$DIRECTORY" ] && bailout
+
+case "$DIRECTORY" in *floppy*)
+DIRECTORY="$FLOPPYDIR"
+KNOPPIXSH="$DIRECTORY/knoppix.sh"
+while :; do
+umountfloppy
+
+MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
+MESSAGE2="Inserte un disquete vacío formateado para DOS o ext2."
+MESSAGE2="Insérez s'il vous plait une disquette déjà formattée DOS ou ext2, et inscriptible."
+MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
+
+$DIALOG --msgbox "$MESSAGE2" 16 51 2 || bailout
+
+echo "$FLOPPYDIR" | grep -q auto || mount /mnt/floppy
+[ "$?" = "0" ] && writescript "$KNOPPIXSH" && break
+done
 ;;
 *)
-SUCCESS="Creation of the KNOPPIX configuration archive was successful. Your configuration files will be reinstalled to the ramdisk on next Oralux boot."
-;;
+ERROR="Leider konnte die KNOPPIX-Konfiguration NICHT gespeichert werden:"
+ERROR="No se pudo guardar la configuración de KNOPPIX:"
+ERROR="La configuration KNOPPIX n'a pu être sauvée :"
+ERROR="The KNOPPIX configuration could NOT be saved:"
+rm -f "$TMP.err"
+mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
+[ "$?" != "0" ] && { $DIALOG --msgbox "$ERROR `cat $TMP.err`" 10 75; bailout; }
+mount | grep -q "$DIRECTORY.*ntfs" && { $DIALOG --title "$TITLE1" --msgbox "$ERROR NTFS" 10 75; bailout; }
+mount -o remount,rw "$DIRECTORY"
+KNOPPIXSH="$DIRECTORY/knoppix.sh"
+writescript "$KNOPPIXSH" "$CONFIGS_FILE"
 esac
+}
 
-touch "$TMP.done" ; wait ; rm -f "$TMP.done"
+MESSAGE1="Wollen Sie Konfigurationsdateien speichern:"
+MESSAGE1="¿Desea guardar los archivos de configuración ?"
+MESSAGE1="Souhaitez-vous sauvegarder les fichiers de configuration ?"
+MESSAGE1="Do you want to save the configuration files?"
 
-[ "$RC" = "0" ] && echo "$SUCCESS" || echo "$ERROR `cat $TMP.err`"
+$DIALOG --yesno "$MESSAGE1" 8 65 || bailout
+
+# Compare the new list of configuration files and the previous one 
+#RAF
+#getOldList
+oldSum=$(md5sum /mnt/sda1/configs.tbz | awk '{printf $1}' )
+
+#RAF
+#tar -jtvf /mnt/sda1/configs.tbz > /tmp/oldlist
+
+SAVEHOME=""
+if [ "/home/knoppix" == "$(find /home/knoppix -maxdepth 0 -fstype tmpfs)" ]
+then
+    SAVEHOME="SAVEHOME"
+fi
+
+getNewList $SAVEHOME
+
+rm -f "$TMP.err"
+BZIP2=-9 tar -T - -cpPjf "/tmp/configs.tbz" <"$newList" 2>"$TMP.err"
+newSum=$(md5sum /tmp/configs.tbz | awk '{printf $1}' )
+
+#RAF
+#echo $newSum
+#tar -jtvf /tmp/configs.tbz > /tmp/newlist
+
+if [ "$newSum" == "$oldSum" ]; then
+#RAF
+echo idem
+else
+#RAF
+echo different
+saveNewList "/tmp/configs.tbz"
+fi
 
 bailout
