*** empty log message ***

diff --git a/oralux/install/packages/knoppix/saveconfig b/oralux/install/packages/knoppix/saveconfig
--- a/oralux/install/packages/knoppix/saveconfig
+++ b/oralux/install/packages/knoppix/saveconfig
@@ -2,111 +2,134 @@
 # saveconfig - create KNOPPIX configuration floppy
 # (C) Klaus Knopper Mar 2002
 # Spanish translation by Luis Llorente, luis.llorente@hispalinux.es
-#
-# Changes for Oralux
-# Sep 2003: 
-# German translations by Guenther Harrasser.
-# Spanish translations by Fernando Pinto da Silva.
-#
-# 2003,2004 Gilles Casse
-# * French translation
-# * The new config is compared to the old one (via their md5sum)
-# * /etc/fstab is not stored
-# * If the (basic) configuration files are saved to the boot floppy, 
-#   cheatcode floppyconfig is added in syslinux.cfg instead of myconf=...
-# * knoppix.sh: once the files are restored, it installs the symbolic links (/etc/sysconfig/symlinks)
-# Nov 2005 (GC): port Knoppix 4.0.2
-#
-#set -v 
-export DIALOG="/usr/bin/php5 /usr/share/oralux/dialog/dialog.php"
-
-# At Yasr init, the speech synthesizer could crash.
-# A minimenu.tmp file must be created.
-touch /tmp/minimenu.tmp
+# Dec 2005: Update for Oralux, Gilles Casse <gcasse@oralux.org>
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 export PATH
 
+XDIALOG_HIGH_DIALOG_COMPAT=1
+export XDIALOG_HIGH_DIALOG_COMPAT
+
 # Get root
 [ "`id -u`" != "0" ] && exec sudo "$0" "$@"
 
-newList=`tempfile 2>/dev/null`
-TMP=`tempfile 2>/dev/null`
+TMP="/tmp/saveconfig.tmp$$"
 
 bailout(){
-rm -f "$newList" "$TMP" "$TMP.err" "/tmp/configs.tbz"
+rm -f "$TMP" "$TMP.done" "$TMP.err"
+umount "$DIRECTORY"
 exit 0
 }
 
+DIALOG="dialog"
+[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"
+
 trap bailout 1 2 3 15
 
-# Just displays the symlink target, does not actually cause the automounter to attempt starting a mount.
-FLOPPYDIR="$(ls -l /mnt/floppy | awk '{print $NF}')"
+# LANGUAGE etc.
+[ -f /etc/sysconfig/knoppix ] && . /etc/sysconfig/knoppix
+[ -z "$LANG" ] && export LANG
+[ -z "$LANGUAGE" ] && export LANGUAGE
+[ -z "$CHARSET" ] && export CHARSET
 
-umountfloppy(){
-#mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
-mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
-}
+DESKTOPKB="$(du -sk $HOME/Desktop 2>/dev/null | awk '{print $1}')"
 
-# Try to mount this filesystem read-only
-trymount(){
-# Check if already mounted
-case "$(cat /proc/mounts)" in *\ $2\ *) return 0;; esac
-# Apparently, mount-aes DOES autodetect AES loopback files.
-[ -b "$1" ] && { mount -t auto -o ro "$1" "$2" 2>/dev/null; RC="$?"; }
-# We need to mount crypto-loop files with initial rw support
-[ -f "$1" ] && { mount -t auto -o loop,rw "$1" "$2" 2>/dev/null; RC="$?"; }
-# Mount succeeded?
-[ "$RC" = "0" ] && return 0
-return 1
-}
+# Language-dependent Messages
+case "$LANGUAGE" in
+de*|at*|ch*)
+TITLE1="KNOPPIX Konfigurationsarchiv anlegen"
+MESSAGE1="Konfigurationsdateien auswählen:"
+MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
+MESSAGE3="Archiviere geänderte Konfigurationsdateien..."
+MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
+E1="Persönliche Einstellungen (Desktop, Programme)"
+E2="Netzwerk Einstellungen (LAN, Modem, ISDN, ASDL)"
+E3="Grafik Subsystem Einstellungen (XF86Config)"
+E4="Weitere systemweite Einstellungen (Drucker etc.)"
+E5="Alle Desktop-Dateien (${DESKTOPKB}kB)"
+ERROR="Leider konnte die KNOPPIX-Konfiguration NICHT gespeichert werden:"
+;;
+es*)
+TITLE1="Crear un archive de configuración de KNOPPIX"
+MESSAGE1="Elija el tipo de archivos de configuración:"
+MESSAGE2="Por favor, inserte un disquete vacío escribible formateado para DOS o ext2."
+MESSAGE3="Grabando archivos de la configuración..."
+MESSAGE4="Seleccione el directorio para guardar los archivos de configuración."
+E1="Configuración personal (escritorio, programas)"
+E2="Configuración de Red (LAN, Modem, RDSI, ADSL)"
+E3="Configuración del subsistema gráfico (XF86Config)"
+E4="Otras configuraciones del sistema (impresora, etc.)"
+E5="Todos los archivos en el Escritorio (${DESKTOPKB}kB)"
+ERROR="No se pudo crear de configuración de KNOPPIX:"
+;;
+fr*)
+TITLE1="Créer une archive de configuration KNOPPIX"
+MESSAGE1="Choisissez le type des fichiers de configuration :"
+MESSAGE2="Introduisez svp une disquette réinscriptible vide formatée en DOS ou ext2."
+MESSAGE3="Sauvegarde de l'archive de configuration..."
+MESSAGE4="Choisissez, s'il vous plait, le répertoire de sauvegarde des fichiers de configuration :"    
+E1="Configuration personelle (bureau, programmes)"
+E2="Configuration réseau (LAN, Modem, RNIS, ADSL)"
+E3="Configuration du sous-système graphique (XF86Config)"
+E4="Autre configuration système (imprimante, etc...)"
+E5="Tous les fichiers du bureau (${DESKTOPKB}kB)"
+ERROR="La configuration KNOPPIX n'a pu être sauvegardé :"
+;;
+*)
+TITLE1="Create KNOPPIX configuration archive"
+MESSAGE1="Chose type of configuration files:"
+MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
+MESSAGE3="Saving configuration archive..."
+MESSAGE4="Please select directory for saving configuration files:"
+E1="Personal configuration (desktop, programs)"
+E2="Network settings (LAN, Modem, ISDN, ADSL)"
+E3="Graphics subsystem settings (XF86Config)"
+E4="Other system configuration (printer etc.)"
+E5="All files on the Desktop (${DESKTOPKB}kB)"
+ERROR="The KNOPPIX configuration could NOT be saved:"
+;;
+esac
 
+#$DIALOG --clear --title "$TITLE1" --checklist "$MESSAGE1" 18 75 9 p "$E1" on d "$E5" off n "$E2" on x "$E3" on o "$E4" on 2>"$TMP" || bailout
+
+FILES=""
+SAVEHOME=""
+SAVEDESK=""
+SAVEETC=""
+SAVENET=""
+SAVEX=""
+CHOWNHOME=""
+NETFILES='/etc/network|/etc/ppp|/etc/chat|/etc/isdn|/etc/sysconfig/isdn|/etc/sysconfig/provider|/etc/resolv\.conf|/etc/hosts|/etc/hosts\.|/etc/inetd\.conf'
+XFILES='/etc/X11'
+# for i in `sed 's,",,g;s,/, ,g;s,'\'',,g;' < "$TMP"`; do
+# case $i in
+# p) SAVEHOME="yes" ;;
+# d) SAVEDESK="yes" ;;
+# n|x|o) SAVEETC="yes"; case "$i" in n) SAVENET="yes";; x) SAVEX="yes";; esac ;;
+# esac
+# done
+
+SAVEHOME="yes"
+SAVEDESK="yes"
+SAVEETC="yes"
+SAVENET="yes"
+SAVEX="yes"
+
+
+[ -n "$SAVEHOME" -o -n "$SAVEDESK" ] && CHOWNHOME="chown -R $(ls -ld $HOME | awk '{print $3"."$4}') $HOME"
+
+# Find changes in (real) files of dir1 ... dir2
 findchanged(){
 if [ -d "$1" ]; then
-for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' | grep -v "~$" )`; do
+for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' )`; do
 cmp -s "$1/$i" "$2/$i" || echo "$1/$i"
-
 done
 elif [ -e "$1" ]; then
 cmp -s "$1" "$2" || echo "$1"
 fi
 }
 
-getNewList(){
-
-    if [ "$1" == "SAVEHOME" ]; then
-	IGNORE="\.ICEauthority|ksycoka|\.xsession-errors|\.DCOP|\.MCOP|kio_http/cache|\.mozilla/.*/Cache/|favicons|office/user/work"
-	for i in $HOME/.??* $HOME/office $HOME/evolution; do findchanged "$i" /etc/skel/$(basename "$i"); done | egrep -v -e '('"$IGNORE"')' > "$newList"
-    fi
-
-#    SAVEDESK=""
-#    [ -n "$SAVEDESK" ] && for i in $HOME/Desktop; do findchanged "$i" /etc/skel/$(basename "$i"); done >> "$newList"
-    
-    IGNORE='/etc/ioctl.save|/etc/fstab|/etc/mtab|/etc/X11/XF86Config-4|/etc/X11/XF86Config'
-    if [ -d /KNOPPIX/etc ]; then
-	findchanged /etc /KNOPPIX/etc | egrep -v -e '('"$IGNORE"')' >>"$newList"
-    fi
-}
-
-# getOldList(){
-#     source /etc/sysconfig/knoppix
-#
-#     MYCONFDEVICE=/dev/sda1
-#     MYCONFMOUNTPOINT=/mnt/sda1
-#     MYCONFDIR=/mnt/sda1
-
-#     if [ -n "$MYCONFDEVICE" ]; then
-# 	if trymount "$MYCONFDEVICE" "$MYCONFMOUNTPOINT"; then
-# 	    MYCONFIG="$(ls -1d $MYCONFDIR/[Cc][Oo][Nn][Ff][Ii][Gg][Ss].[Tt][Bb][Zz] 2>/dev/null)"
-# 	    if [ -n "$MYCONFIG" -a -f "$MYCONFIG" ]; then
-# 		tar -jpPtf "$MYCONFIG" > $oldList
-# 	    fi
-# 	fi
-#     fi
-# }
-
 writescript(){
-CONFIGSFILE=$2
 cat >"$1" <<EOT
 #!/bin/sh
 [ "\`id -u\`" = "0" ] || { echo "You need root privileges to modify the system!" >&2 ; exit 1; }
@@ -114,20 +137,87 @@ cat >"$1" <<EOT
 [ -f "\$CONFIGS" ] || CONFIGS="/cdrom/KNOPPIX/configs.tbz"
 [ -f "\$CONFIGS" ] || CONFIGS="/mnt/floppy/configs.tbz"
 if [ -f "\$CONFIGS" ]; then
-echo "Extracting config archive \$CONFIGS..."
+echo "[1mExtracting config archive \$CONFIGS...[0m"
 tar -jpPtf "\$CONFIGS" | while read i; do rm -f "\$i"; done
 tar -jpPxf "\$CONFIGS" ; $CHOWNHOME
 fi
+EOT
+return "$?"
+}
 
-# Restoring the symlinks
-symlinksfile="/etc/sysconfig/symlinks"
-if [ -e "\$symlinksfile" ]; then
-bash "\$symlinksfile" 
+# Just displays the symlink target, does not actually cause the automounter to attempt starting a mount.
+FLOPPYDIR="$(ls -l /mnt/floppy | awk '{print $NF}')"
+
+umountfloppy(){
+mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
+}
+
+# Directory selector
+PARTITIONS="/mnt/floppy [Floppy] on"
+for i in `awk '/^\/dev\/([hs]d|ub)[a-z].*\/mnt\/([hs]d|ub)[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`; do
+PARTITIONS="$PARTITIONS ${i} [Disk/Partition] off"
+done
+
+
+rm -f "$TMP"
+$DIALOG --clear --title "$TITLE1" --radiolist "$MESSAGE4" 18 75 9 $PARTITIONS 2>"$TMP" || bailout
+
+DIRECTORY="$(<$TMP)"
+[ -z "$DIRECTORY" -o ! -e "$DIRECTORY" ] && bailout
+
+case "$DIRECTORY" in *floppy*)
+DIRECTORY="$FLOPPYDIR"
+KNOPPIXSH="$DIRECTORY/knoppix.sh"
+while :; do
+umountfloppy
+$DIALOG --title "$TITLE1" --yesno "$MESSAGE2" 8 65 || bailout
+echo "$FLOPPYDIR" | grep -q auto || mount /mnt/floppy
+[ "$?" = "0" ] && writescript "$KNOPPIXSH" && break
+done
+;;
+*)
+rm -f "$TMP.err"
+mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
+[ "$?" != "0" ] && { $DIALOG --title "$TITLE1" --msgbox "$ERROR `cat $TMP.err`" 10 75; bailout; }
+mount | grep -q "$DIRECTORY.*ntfs" && { $DIALOG --title "$TITLE1" --msgbox "$ERROR NTFS" 10 75; bailout; }
+mount -o remount,rw "$DIRECTORY"
+KNOPPIXSH="$DIRECTORY/knoppix.sh"
+writescript "$KNOPPIXSH"
+esac
+
+gpid=""
+
+gauge(){
+status=0
+while [ ! -e "$TMP.done" ]; do echo "$status" ; status="`expr \( 100 - $status \) / 4 + $status`"; sleep 2; done | $DIALOG --title "$TITLE1" --gauge "$MESSAGE3" 8 65 0
+}
+
+# Start status bar
+# if [ "$DIALOG" = "dialog" ]; then
+gauge &
+# else
+## Gauge doesn't work yet with gdialog
+# $DIALOG --title "$TITLE1" --gauge "$MESSAGE3" 8 65 75 &
+# gpid="$!"
+# fi
+
+rm -f "$TMP"
+touch "$TMP"
+
+[ -n "$SAVEHOME" ] && for i in $HOME/.??* $HOME/office $HOME/evolution; do findchanged "$i" /etc/skel/$(basename "$i"); done | egrep -v -e '(\.ICEauthority|ksycoka|\.xsession-errors|\.DCOP|\.MCOP|kio_http/cache|\.mozilla/.*/Cache/|favicons|office/user/work)' >"$TMP"
+[ -n "$SAVEDESK" ] && for i in $HOME/Desktop; do findchanged "$i" /etc/skel/$(basename "$i"); done >>"$TMP"
+
+IGNORE='/etc/ioctl.save|/etc/mtab'
+
+if [ -n "$SAVEETC" -a -d /KNOPPIX/etc ]; then
+findchanged /etc /KNOPPIX/etc >>"$TMP"
+[ -n "$SAVENET" ] || IGNORE="$IGNORE|$NETFILES"
+[ -n "$SAVEX" ] || IGNORE="$IGNORE|$XFILES"
 fi
 
-chown knoppix:knoppix /home/knoppix/.*
-
-EOT
+rm -f "$TMP.tmp"
+egrep -v -e '('"$IGNORE"')' "$TMP" > "$TMP.tmp"
+mv -f "$TMP.tmp" "$TMP"
 
 SCRIPTS=""
 STARTNET=""
@@ -142,122 +232,59 @@ case "$i" in
 /etc/cups*) STARTCUPS="yes";;
 /etc/inittab) REINIT="yes";;
 esac
-done <"$newList"
+done <"$TMP"
 
-[ -n "$STARTNET" ] && { echo "killall pump 2>/dev/null && sleep 2 && killall -9 pump 2>/dev/null && sleep 2" >>"$KNOPPIXSH" ; SCRIPTS="$SCRIPTS ifupdown networking"; }
-[ -n "$STARTPCMCIA" ] && echo 'echo "(Re)starting PCMCIA services."; killall cardmgr 2>/dev/null && sleep 4; cardmgr && sleep 4' >>"$KNOPPIXSH"
-[ -n "$STARTCUPS" ] && SCRIPTS="$SCRIPTS cupsys"
+
+[ -n "$STARTNET" ]    && { echo "killall pump 2>/dev/null && sleep 2 && killall -9 pump 2>/dev/null && sleep 2" >>"$KNOPPIXSH" ; SCRIPTS="$SCRIPTS ifupdown networking"; }
+[ -n "$STARTPCMCIA" ] && echo 'echo "[1m(Re)starting PCMCIA services.[0m"; killall cardmgr 2>/dev/null && sleep 4; cardmgr && sleep 4' >>"$KNOPPIXSH"
+[ -n "$STARTCUPS" ]   && SCRIPTS="$SCRIPTS cupsys"
 
 if [ -n "$SCRIPTS" ]; then
-echo 'echo "Starting daemons..."' >>"$KNOPPIXSH"
+echo 'echo "[1mStarting daemons...[0m"' >>"$KNOPPIXSH"
 echo "for i in $SCRIPTS; do [ -x /etc/init.d/\$i ] && /etc/init.d/\$i start; done" >>"$KNOPPIXSH"
 fi
 
-[ -n "$REINIT" ] && echo 'echo "Reloading INIT." ; init q' >> "$KNOPPIXSH"
+[ -n "$REINIT" ] && echo 'echo "[1mReloading INIT.[0m" ; init q' >> "$KNOPPIXSH"
 
 rm -f "$TMP.err"
-#BZIP2=-9 tar -T - -cpPjf "$DIRECTORY/configs.tbz" <"$newList" 2>"$TMP.err"
-
-cp "$CONFIGSFILE" "$DIRECTORY/configs.tbz"
+BZIP2=-9 tar -T - -cpPjf "$DIRECTORY/configs.tbz" <"$TMP" 2>"$TMP.err"
 
 RC="$?"
 
 if [ "$DIRECTORY" = "$FLOPPYDIR" ]; then
-
-if [ -e "$DIRECTORY/syslinux.cfg" ]; then
-# We use the floppyconfig cheatcode
-sed "s;[^ ]*conf[^=]*=[^ ]*/[^ ]*;floppyconfig;g" "$DIRECTORY/syslinux.cfg" > $TMP
-mv -f $TMP "$DIRECTORY/syslinux.cfg" 2>/dev/null
-fi
-
 umountfloppy
-else 
-# Not saved on floppy
-umount "$DIRECTORY" 2>/dev/null
-
-# RAF (GC): if there is a boot floppy, force the cheatcode to myconf=scan
-# sed "s;floppyconf[^ ]*;myconf=scan;g"
-
+else
+umount "$DIRECTORY"
 fi
-}
 
-saveNewList(){
-CONFIGS_FILE=$1
-
-MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
-MESSAGE4="Seleccione el directorio para guardar los archivos de configuración."
-MESSAGE4="Choisissez, s'il vous plait, le répertoire de sauvegarde des fichiers de configuration :"    
-MESSAGE4="Please select directory for saving configuration files:"
-
-# Directory selector
-PARTITIONS="/mnt/floppy [Floppy] on"
-for i in `awk '/^\/dev\/([hs]d|ub)[a-z].*\/mnt\/([hs]d|ub)[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`; do
-PARTITIONS="$PARTITIONS ${i} [Disk/Partition] off"
-done
-
-rm -f "$TMP"
-$DIALOG --clear --radiolist "$MESSAGE4" 18 75 9 $PARTITIONS 2>"$TMP" || bailout
-
-DIRECTORY=`cat $TMP`
-
-[ -z "$DIRECTORY" -o ! -e "$DIRECTORY" ] && bailout
-
+BOOTOPT="knoppix myconfig=$DIRECTORY"
+AUTO="knoppix myconfig=scan"
 case "$DIRECTORY" in *floppy*)
-DIRECTORY="$FLOPPYDIR"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-while :; do
-umountfloppy
+ BOOTOPT="knoppix floppyconfig"
+ AUTO=""
+esac
 
-MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
-MESSAGE2="Inserte un disquete vacío formateado para DOS o ext2."
-MESSAGE2="Insérez s'il vous plait une disquette déjà formattée DOS ou ext2, et inscriptible."
-MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
-
-$DIALOG --msgbox "$MESSAGE2" 16 51 2 || bailout
-
-echo "$FLOPPYDIR" | grep -q auto || mount /mnt/floppy
-[ "$?" = "0" ] && writescript "$KNOPPIXSH" "$CONFIGS_FILE" && break
-done
+# More language-dependent Messages
+case "$LANGUAGE" in
+de*|at*|ch*)
+[ -n "$AUTO" ] && AUTO=" bzw. \"$AUTO\" (automatische Suche)"
+SUCCESS="Die KNOPPIX-Konfiguration wurde erfolgreich gespeichert. Ihre Konfigurationsdateien werden beim nächsten KNOPPIX-Bootvorgang in die Ramdisk restauriert, wenn Sie im Bootscreen \"$BOOTOPT\"$AUTO angeben."
+;;
+es*)
+[ -n "$AUTO" ] && AUTO=" o \"$AUTO\" (automatic)"
+SUCCESS="La creación del configuración de KNOPPIX fue satisfactoria. Sus archivos de configuración serán reinstalados en el siguiente arranque de KNOPPIX si especifica \"$BOOTOPT\"$AUTO en la línea de comandos del arranque."
 ;;
 *)
-ERROR="Leider konnte die KNOPPIX-Konfiguration NICHT gespeichert werden:"
-ERROR="No se pudo guardar la configuración de KNOPPIX:"
-ERROR="La configuration KNOPPIX n'a pu être sauvée :"
-ERROR="The KNOPPIX configuration could NOT be saved:"
-rm -f "$TMP.err"
-mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
-[ "$?" != "0" ] && { $DIALOG --msgbox "$ERROR `cat $TMP.err`" 10 75; bailout; }
-mount | grep -q "$DIRECTORY.*ntfs" && { $DIALOG --title "$TITLE1" --msgbox "$ERROR NTFS" 10 75; bailout; }
-mount -o remount,rw "$DIRECTORY"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-writescript "$KNOPPIXSH" "$CONFIGS_FILE"
+[ -n "$AUTO" ] && AUTO=", or \"$AUTO\" (automatic search)"
+SUCCESS="Creation of the KNOPPIX configuration archive was successful. Your configuration files will be reinstalled to the ramdisk on next KNOPPIX boot if you specify \"$BOOTOPT\"$AUTO at the boot prompt."
+;;
 esac
-}
 
-MESSAGE1="Wollen Sie Konfigurationsdateien speichern:"
-MESSAGE1="¿Desea guardar los archivos de configuración ?"
-MESSAGE1="Souhaitez-vous sauvegarder les fichiers de configuration ?"
-MESSAGE1="Do you want to save the configuration files?"
 
-#$DIALOG --yesno "$MESSAGE1" 8 65 || bailout
+# Stop status bar
+# [ "$DIALOG" = "dialog" ] && { touch "$TMP.done" ; wait ; rm -f "$TMP.done" ; } || { [ -n "$gpid" ] && kill "$gpid" 2>/dev/null; sleep 1; }
+touch "$TMP.done" ; wait ; rm -f "$TMP.done"
 
-# Compare the new list of configuration files and the previous one 
-
-SAVEHOME=""
-if [ "/home/knoppix" == "$(find /home/knoppix -maxdepth 0 -fstype tmpfs)" ]
-then
-    SAVEHOME="SAVEHOME"
-fi
-
-getNewList $SAVEHOME
-
-rm -f "$TMP.err"
-BZIP2=-9 tar -T - -cpPjf "/tmp/configs.tbz" <"$newList" 2>"$TMP.err"
-newSum=$(md5sum /tmp/configs.tbz | awk '{printf $1}' )
-
-source /etc/sysconfig/knoppix
-if [ "$newSum" != "$CONFIGMD5" ]; then
-    saveNewList "/tmp/configs.tbz"
-fi
+[ "$RC" = "0" ] && $DIALOG --title "$TITLE1" --msgbox "$SUCCESS" 12 65 || $DIALOG --title "$TITLE1" --msgbox "$ERROR `cat $TMP.err`" 10 75
 
 bailout
